// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwak5N6uuAqXrIj2vltfTgKg_bIZSGGSg',
    appId: '1:566262242519:web:7ebc8a8a2bf3433c6ea492',
    messagingSenderId: '566262242519',
    projectId: 'hedieaty-eae86',
    authDomain: 'hedieaty-eae86.firebaseapp.com',
    storageBucket: 'hedieaty-eae86.firebasestorage.app',
    measurementId: 'G-NH14DGGNJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt1FgBrcDRJbYDS249YqvlCw59iWJ1e0s',
    appId: '1:566262242519:android:32494c130432b9b46ea492',
    messagingSenderId: '566262242519',
    projectId: 'hedieaty-eae86',
    storageBucket: 'hedieaty-eae86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuORL4igSNNj4HFJiI01iJbm5ogWKPulc',
    appId: '1:566262242519:ios:64a313d40128b8d96ea492',
    messagingSenderId: '566262242519',
    projectId: 'hedieaty-eae86',
    storageBucket: 'hedieaty-eae86.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuORL4igSNNj4HFJiI01iJbm5ogWKPulc',
    appId: '1:566262242519:ios:64a313d40128b8d96ea492',
    messagingSenderId: '566262242519',
    projectId: 'hedieaty-eae86',
    storageBucket: 'hedieaty-eae86.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwak5N6uuAqXrIj2vltfTgKg_bIZSGGSg',
    appId: '1:566262242519:web:2398051695e9287b6ea492',
    messagingSenderId: '566262242519',
    projectId: 'hedieaty-eae86',
    authDomain: 'hedieaty-eae86.firebaseapp.com',
    storageBucket: 'hedieaty-eae86.firebasestorage.app',
    measurementId: 'G-PEZ20JVNRR',
  );

}